### ISSUE TITLE
Create unit tests for endpoints

### ISSUE THREAD

**Issue by IsaacCheng9** [IsaacCheng9/fairsplit#32]
## Specification
- We need to create unit tests to ensure that our commits aren't breaking any features.
  - Look into implementing tests using a framework such as Jest.

## Steps
- [x] `users.test.js` – [PR #73](https://github.com/IsaacCheng9/fairsplit/pull/73)
- [x] `debts.test.js` – [PR #74](https://github.com/IsaacCheng9/fairsplit/pull/74)
- [x] `expenses.test.js` – [PR #75](https://github.com/IsaacCheng9/fairsplit/pull/75)
